### ISSUE TITLE
Frigate+ API Key in Frigate LXC

### ISSUE THREAD

**Issue by wimb0** [remz1337/Proxmox#11]
How do I add the Frigate+ API Key to Frigate LXC, to add and activate the Plus API?

I Updated the config to include Frigate+ model path.
Frigate won't start.

```
2024-10-07 10:19:58.172528  [INFO] Preparing Frigate...
2024-10-07 10:19:58.172597  [INFO] Starting Frigate...
2024-10-07 10:19:59.473253  [2024-10-07 10:19:59] frigate.app                    INFO    : Starting Frigate (0.14.1-)
2024-10-07 10:19:59.478520  [2024-10-07 10:19:59] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-07 10:19:59.523695  [2024-10-07 10:19:59] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-07 10:19:59.554443  *************************************************************
2024-10-07 10:19:59.554495  *************************************************************
2024-10-07 10:19:59.554512  ***    Your config file is not valid!                     ***
2024-10-07 10:19:59.554527  ***    Please check the docs at                           ***
2024-10-07 10:19:59.554542  ***    https://docs.frigate.video/configuration/index     ***
2024-10-07 10:19:59.554556  *************************************************************
2024-10-07 10:19:59.554570  *************************************************************
2024-10-07 10:19:59.554585  ***    Config Validation Errors                           ***
2024-10-07 10:19:59.554600  *************************************************************
2024-10-07 10:19:59.554614  Plus API not activated
2024-10-07 10:19:59.554870  Traceback (most recent call last):
2024-10-07 10:19:59.554941    File "/opt/frigate/frigate/app.py", line 645, in start
2024-10-07 10:19:59.554960      self.init_config()
2024-10-07 10:19:59.554976    File "/opt/frigate/frigate/app.py", line 140, in init_config
2024-10-07 10:19:59.554991      self.config = user_config.runtime_config(self.plus_api)
2024-10-07 10:19:59.555007    File "/opt/frigate/frigate/config.py", line 1599, in runtime_config
2024-10-07 10:19:59.555023      config.model.check_and_load_plus_model(plus_api)
2024-10-07 10:19:59.555038    File "/opt/frigate/frigate/detectors/detector_config.py", line 91, in check_and_load_plus_model
2024-10-07 10:19:59.555067      download_url = plus_api.get_model_download_url(model_id)
2024-10-07 10:19:59.555081    File "/opt/frigate/frigate/plus.py", line 228, in get_model_download_url
2024-10-07 10:19:59.555096      r = self._get(f"model/{model_id}/signed_url")
2024-10-07 10:19:59.555110    File "/opt/frigate/frigate/plus.py", line 84, in _get
2024-10-07 10:19:59.555124      f"{self.host}/v1/{path}", headers=self._get_authorization_header()
2024-10-07 10:19:59.555139    File "/opt/frigate/frigate/plus.py", line 79, in _get_authorization_header
2024-10-07 10:19:59.555153      self._refresh_token_if_needed()
2024-10-07 10:19:59.555168    File "/opt/frigate/frigate/plus.py", line 71, in _refresh_token_if_needed
2024-10-07 10:19:59.555182      raise Exception("Plus API not activated")
2024-10-07 10:19:59.555197  Exception: Plus API not activated
2024-10-07 10:19:59.555211  
2024-10-07 10:19:59.555226  *************************************************************
2024-10-07 10:19:59.555241  ***    End Config Validation Errors                       ***
2024-10-07 10:19:59.555255  *************************************************************
```

**Comment by 3h50** [comment]
Found https://github.com/tteck/Proxmox/discussions/2711#discussioncomment-8975702 in my search

**Comment by wimb0** [comment]
Interesting! I tried that, but that does not seem to work.

Did edit `/etc/systemd/system/frigate.service`
Add line: `Environment=plus_api_key=verylongapikey` under [Service] 
After that: `systemctl daemon-reload`
Then a reboot.
Unfortunately still the same problem: `Exception: Plus API not activated`

**Comment by SubNoizey** [comment]
keen to see if we can get an answer

**Comment by carlosduque-incoxe** [comment]
@tteck
For me, editing `/etc/systemd/system/frigate.service` WORKED!!
I needed to put in capital letters and reboot.

What I did:

edit `/etc/systemd/system/frigate.service`
Add line: `Environment=PLUS_API_KEY=verylongapikey` under [Service]
After that: `systemctl daemon-reload`
Then a reboot.

![image](https://github.com/user-attachments/assets/be5104d1-badb-44b6-b2ba-8678d751ab0b)

**Comment by SubNoizey** [comment]
> @tteck For me, editing `/etc/systemd/system/frigate.service` WORKED!! I needed to put in capital letters and reboot.
> 
> What I did:
> 
> edit `/etc/systemd/system/frigate.service` Add line: `Environment=PLUS_API_KEY=verylongapikey` under [Service] After that: `systemctl daemon-reload` Then a reboot.
> 
> ![image](https://private-user-images.githubusercontent.com/155538710/376321304-be5104d1-badb-44b6-b2ba-8678d751ab0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NDE3NDEsIm5iZiI6MTcyODk0MTQ0MSwicGF0aCI6Ii8xNTU1Mzg3MTAvMzc2MzIxMzA0LWJlNTEwNGQxLWJhZGItNDRiNi1iMmJhLTg2NzhkNzUxYWIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQyMTMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzM1MGRhMDY0MjMzMjZiM2YwNDA4Zjk1ODU3N2E2NDc1N2MxZmI4OWRjYWJmNzVlZGI1MDM5MDg5Y2NlYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u5WxWxRWr01jwIz8uk_-T1DxrB4ALVA_GK5qXFSJ6pU)

@tteck maybe you could add this to the bottom of https://tteck.github.io/Proxmox/#frigate-lxc ??

**Comment by remz1337** [comment]
not sure why I didn't get notified on this. Indeed adding the key to the service is the way to go (my fork already has a commented line for that. See [here](https://github.com/remz1337/Proxmox/blob/1daa02fa26b67a985722dc1c16d8e2411323fd8f/install/frigate-install.sh#L334C1-L334C50) for that

Closing this issue as resolved
